# -- Number of replicas if HPA is not enabled
replicaCount: 1

image:
  repository: "buildkitd"
  image: "moby/buildkit"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.14.1"

imagePullSecrets: []

resources:
  requests:
    cpu: '1'
    memory: '128Mi'
  limits:
    cpu: '4'
    memory: '256Mi'

rootless: 
  enabled: true

tls: 
  enabled: false

Bottlerocket: 
  # if you use bottlerocket base image for yours EKS/AKS, you need specific additionals options which need to
  # be setted on your node/vm
  enabled: true
  image:
    repository: 
    image: "alpine"
    tag: "3.20.1"

customOptions:
  runOnEks: true
  runOnBottlerocketOS:


autoscaling:  
  # -- enable HPA
  enabled: true
  # -- HPA min replicas
  minReplicas: 1
  # -- HPA max replicas
  maxReplicas: 10
  # -- Upscaling policy for CPU tracking
  targetCPUUtilizationPercentage: 80
  # -- Upscaling policy for memory tracking
  targetMemoryUtilizationPercentage: 80