replicaCount: 1

image:
  repository: "buildkitd"
  image: "moby/buildkit"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.14.1-rootless"

imagePullSecrets: []

resources:
  requests:
    cpu: '1'
    memory: '128Mi'
  limits:
    cpu: '4'
    memory: '256Mi'


autoscaling:  
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80