name: cicd

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  helm-lint:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: '3.14.0'

    - name: Helm Lint
      run: |
        for chart in charts/*; do
          if [ -d "$chart" ]; then
            helm lint "$chart"
          fi
        done

  kubeconform:
    runs-on: ubuntu-20.04
    needs: helm-lint
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-summary -output json kubeconfigs/"